# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R vignette on macs

on: 
  workflow_dispatch:
    branches: [master, dev]
  
permissions: write-all
 

jobs:
  build:
    runs-on: macos-latest
    

    steps:
      - run: brew install --cask xquartz
      - uses: actions/checkout@v4
      - name: Set up R 
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: devtools, cpp11
      - name: Build Vignettes
        run: |
          devtools::load_all(".")
          renv::status()
          devtools::build_vignettes()
        shell: Rscript {0}
